services:
  mysql:
    init: true
    image: mysql:5.7-debian
    platform: linux/amd64
    ports: ["${PORT_MYSQL}:${iPORT_MYSQL}"]
    environment:
      MYSQL_ROOT_HOST:      "%"
      MYSQL_DATABASE:       ${MYSQL_DATABASE}
      MYSQL_USER:           ${MYSQL_USER}
      MYSQL_PASSWORD:       ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
