services:
  # CODE SOURCE: https://medium.com/tekraze/running-kafka-in-docker-compose-2824b7c6aa9a
  # kafka: #9092.running, but missing topic for crane
  # zookeeper: #2181.running required for kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    platform: linux/amd64
    ports: ["2181:2181"]
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    platform: linux/amd64
    ports: ["${PORT_KAFKA}:${iPORT_KAFKA}"]
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:${iPORT_KAFKA}
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    volumes:
      - ./kafka/data:/var/lib/kafka/data
      - ./kafka/init.sh:/init.sh