services:
  postgres:
    image: postgres:17.4
    ports: ["${iPORT_POSTGRES}:${PORT_POSTGRES}"]
    environment: 
      POSTGRES_PASSWORD: pile7113
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
